### ISSUE TITLE
Yemek saat aralıkları

### ISSUE THREAD

**Issue by erkanvatan** [bariscanyilmaz/ytuyemekhane-telegram-bot#1]
/help menüsüne yemek saat aralıklarını gösterecek bir komut eklenebilir. Güzel uygulama, eline sağlık.

**Comment by bariscanyilmaz** [comment]
@arensonzz teşekkür ederim. `enhancement` olarak label ekliyorum. bu haftasonu eklerim müsait olduğum bir zamanda.
